export const GET_DATA_REQUEST = 'GET_DATA_REQUEST'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export const GET_DATA_ERROR = 'GET_DATA_ERROR'

export const SCHEDULE_POST_REQUEST = 'SCHEDULE_POST_REQUEST'
export const SCHEDULE_POST_SUCCESS = 'SCHEDULE_POST_SUCCESS'
export const SCHEDULE_POST_ERROR = 'SCHEDULE_POST_ERROR'

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_ERROR = 'EDIT_POST_ERROR'

export const REMOVE_POST_REQUEST = 'REMOVE_POST_REQUEST'
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS'
export const REMOVE_POST_ERROR = 'REMOVE_POST_ERROR'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
